from PyQt5 import Qt
from PyQt5.QtWidgets import (QLabel, QLineEdit,
                             QFrame,  QPushButton,
                             QRadioButton, QCheckBox)
from PyQt5.QtCore import QRect, QCoreApplication, QSize, Qt
from templateCSS import CSS
# from windowstomodel import commands


class Order:
    def __int__(self):
        self.label_order_prefix = QLabel()
        self.label_order_number = QLabel()
        self.label_data_create = QLabel()
        self.label_vin_code_txt = QLabel()
        self.label_car_number_txt = QLabel()
        self.label_car_brand_txt = QLabel()
        self.label_client_name_txt = QLabel()
        self.label_client_full_name_txt = QLabel()
        self.label_car_model_txt = QLabel()
        self.radioButton_order_close = QRadioButton()
        self.radioButton_car = QRadioButton()
        self.radioButton_part = QRadioButton()
        self.checkBox = QCheckBox()
        self.checkBox_2 = QCheckBox()
        self.checkBox_3 = QCheckBox()
        self.checkBox_4 = QCheckBox()
        self.pushButton_order_close = QPushButton()
        self.pushButton_new_client = QPushButton()
        self.pushButton_new_car = QPushButton()
        self.pushButton_print = QPushButton()
        self.lineEdit_FIO_owner = QLineEdit()
        self.lineEdit_job_title_owner = QLineEdit()

    # def add_functions(self):
    #     # Ui_MainWindow.order.pushButton_print.clicked.connect(lambda: self.action_to_change_window(Ui_MainWindow.order.pushButton_print))
    #     # Ui_MainWindow.order.pushButton_order_close.clicked.connect(
    #     #     lambda: self.action_to_change_window(Ui_MainWindow.order.pushButton_order_close)
    #     # )
    #     self.pushButton_new_client.clicked.connect(
    #         lambda: commands.action_to_change_window(self.pushButton_new_client, 'новый клиент')
    #     )
    #     self.pushButton_new_car.clicked.connect(
    #         lambda: commands.action_to_change_window(self.pushButton_new_car, 'новая машина')
    #     )


        
    def set_body(self, frame):
        self.frame_order = QFrame(frame)
        self.frame_order.setEnabled(True)
        self.frame_order.setGeometry(QRect(0, 30, 420, 490))
        self.frame_order.setFrameShape(QFrame.StyledPanel)
        self.frame_order.setFrameShadow(QFrame.Raised)
        self.frame_order.setObjectName("frame_order")

        self.label_data_create = QLabel(self.frame_order)
        self.label_data_create.setEnabled(True)
        self.label_data_create.setGeometry(QRect(10, 20, 106, 20))
        self.label_data_create.setFont(CSS.set_font(14))
        self.label_data_create.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_data_create.setInputMethodHints(Qt.ImhDate)
        self.label_data_create.setObjectName("label_data_create")

        self.label_order_number = QLabel(self.frame_order)
        self.label_order_number.setEnabled(True)
        self.label_order_number.setGeometry(QRect(160, 20, 61, 20))
        self.label_order_number.setFont(CSS.set_font(14))
        self.label_order_number.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_order_number.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.label_order_number.setObjectName("label_order_number")

        self.label_order_prefix = QLabel(self.frame_order)
        self.label_order_prefix.setEnabled(True)
        self.label_order_prefix.setGeometry(QRect(240, 20, 21, 20))
        self.label_order_prefix.setFont(CSS.set_font(14))
        self.label_order_prefix.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_order_prefix.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.label_order_prefix.setObjectName("label_order_prefix")
        
        self.label_client_name_txt = QLabel(self.frame_order)
        self.label_client_name_txt.setEnabled(True)
        self.label_client_name_txt.setGeometry(QRect(120, 80, 241, 20))
        self.label_client_name_txt.setFont(CSS.set_font(12, True, 75))
        self.label_client_name_txt.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_client_name_txt.setObjectName("self.label_client_name_txt")

        self.label_client_full_name_txt = QLabel(self.frame_order)
        self.label_client_full_name_txt.setEnabled(True)
        self.label_client_full_name_txt.setGeometry(QRect(120, 110, 241, 20))
        self.label_client_full_name_txt.setFont(CSS.set_font(12, True, 75))
        self.label_client_full_name_txt.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_client_full_name_txt.setObjectName("label_client_full_name_txt")

        self.lineEdit_FIO_owner = QLineEdit(self.frame_order)
        self.lineEdit_FIO_owner.setEnabled(True)
        self.lineEdit_FIO_owner.setGeometry(QRect(120, 140, 281, 20))
        self.lineEdit_FIO_owner.setFont(CSS.set_font(12))
        self.lineEdit_FIO_owner.setObjectName("lineEdit_FIO_owner")

        self.lineEdit_job_title_owner = QLineEdit(self.frame_order)
        self.lineEdit_job_title_owner.setEnabled(True)
        self.lineEdit_job_title_owner.setGeometry(QRect(120, 170, 281, 20))
        self.lineEdit_job_title_owner.setFont(CSS.set_font(12))
        self.lineEdit_job_title_owner.setObjectName("lineEdit_job_title_owner")

        self.label_car_brand_txt = QLabel(self.frame_order)
        self.label_car_brand_txt.setEnabled(True)
        self.label_car_brand_txt.setGeometry(QRect(120, 240, 151, 20))
        self.label_car_brand_txt.setFont(CSS.set_font(12, True, 75))
        self.label_car_brand_txt.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_car_brand_txt.setObjectName("label_car_brand_txt")

        self.label_car_number_txt = QLabel(self.frame_order)
        self.label_car_number_txt.setEnabled(True)
        self.label_car_number_txt.setGeometry(QRect(280, 240, 121, 20))
        self.label_car_number_txt.setFont(CSS.set_font(12, True, 75))
        self.label_car_number_txt.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_car_number_txt.setObjectName("label_car_number_txt")

        self.label_car_model_txt = QLabel(self.frame_order)
        self.label_car_model_txt.setEnabled(True)
        self.label_car_model_txt.setGeometry(QRect(120, 270, 241, 20))
        self.label_car_model_txt.setFont(CSS.set_font(12, True, 75))
        self.label_car_model_txt.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_car_model_txt.setObjectName("label_car_model_txt")

        self.label_vin_code_txt = QLabel(self.frame_order)
        self.label_vin_code_txt.setEnabled(True)
        self.label_vin_code_txt.setGeometry(QRect(120, 300, 241, 20))
        self.label_vin_code_txt.setFont(CSS.set_font(12, True, 75))
        self.label_vin_code_txt.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_vin_code_txt.setObjectName("self.label_vin_code_txt")

        self.radioButton_order_close = QRadioButton(self.frame_order)
        self.radioButton_order_close.setEnabled(True)
        self.radioButton_order_close.setGeometry(QRect(290, 10, 31, 41))
        self.radioButton_order_close.setMinimumSize(QSize(0, 0))
        self.radioButton_order_close.setSizeIncrement(QSize(0, 0))
        self.radioButton_order_close.setBaseSize(QSize(0, 0))
        self.radioButton_order_close.setFont(CSS.set_font(14))
        self.radioButton_order_close.setText("")
        self.radioButton_order_close.setIconSize(QSize(20, 20))
        self.radioButton_order_close.setObjectName("radioButton_order_close")

        self.radioButton_car = QRadioButton(self.frame_order)
        self.radioButton_car.setEnabled(True)
        self.radioButton_car.setGeometry(QRect(120, 210, 67, 16))
        self.radioButton_car.setFont(CSS.set_font(12))
        self.radioButton_car.setObjectName("radioButton_car")

        self.radioButton_part = QRadioButton(self.frame_order)
        self.radioButton_part.setEnabled(True)
        self.radioButton_part.setGeometry(QRect(200, 210, 67, 16))
        self.radioButton_part.setFont(CSS.set_font(12))
        self.radioButton_part.setObjectName("radioButton_part")

        self.checkBox = QCheckBox(self.frame_order)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QRect(60, 350, 171, 16))
        self.checkBox.setFont(CSS.set_font(12))
        self.checkBox.setStyleSheet("alternate-background-color: rgb(195, 195, 195);")
        self.checkBox.setObjectName("checkBox")

        self.checkBox_2 = QCheckBox(self.frame_order)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setGeometry(QRect(60, 380, 171, 16))
        self.checkBox_2.setFont(CSS.set_font(12))
        self.checkBox_2.setStyleSheet("alternate-background-color: rgb(195, 195, 195);")
        self.checkBox_2.setObjectName("checkBox_2")

        self.checkBox_3 = QCheckBox(self.frame_order)
        self.checkBox_3.setEnabled(True)
        self.checkBox_3.setGeometry(QRect(60, 410, 171, 16))
        self.checkBox_3.setFont(CSS.set_font(12))
        self.checkBox_3.setStyleSheet("alternate-background-color: rgb(195, 195, 195);")
        self.checkBox_3.setObjectName("checkBox_3")

        self.checkBox_4 = QCheckBox(self.frame_order)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setGeometry(QRect(60, 440, 171, 16))
        self.checkBox_4.setFont(CSS.set_font(12))
        self.checkBox_4.setStyleSheet("alternate-background-color: rgb(195, 195, 195);")
        self.checkBox_4.setObjectName("checkBox_4")

        self.pushButton_order_close = QPushButton(self.frame_order)
        self.pushButton_order_close.setEnabled(True)
        self.pushButton_order_close.setGeometry(QRect(305, 20, 91, 21))
        self.pushButton_order_close.setFont(CSS.set_font(14))
        self.pushButton_order_close.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_order_close.setObjectName("pushButton_order_close")

        self.pushButton_new_client = QPushButton(self.frame_order)
        self.pushButton_new_client.setEnabled(True)
        self.pushButton_new_client.setGeometry(QRect(365, 80, 36, 51))
        self.pushButton_new_client.setStyleSheet("background-color: rgb(205, 205, 205);")
        self.pushButton_new_client.setObjectName("pushButton_new_client_ord")

        self.pushButton_new_car = QPushButton(self.frame_order)
        self.pushButton_new_car.setEnabled(True)
        self.pushButton_new_car.setGeometry(QRect(365, 270, 36, 51))
        self.pushButton_new_car.setStyleSheet("background-color: rgb(205, 205, 205);")
        self.pushButton_new_car.setObjectName("pushButton_new_car")

        self.pushButton_print = QPushButton(self.frame_order)
        self.pushButton_print.setEnabled(True)
        self.pushButton_print.setGeometry(QRect(320, 380, 81, 51))
        self.pushButton_print.setFont(CSS.set_font(12))
        self.pushButton_print.setStyleSheet("background-color: rgb(205, 205, 205);")
        self.pushButton_print.setObjectName("pushButton_print")

        self.label()
        # self.add_functions()
        self.retranslateUi()
        frame.show()
        
    def label(self):
        line_hord_1 = QFrame(self.frame_order)
        line_hord_1.setEnabled(True)
        line_hord_1.setGeometry(QRect(10, 0, 390, 16))
        line_hord_1.setLineWidth(2)
        line_hord_1.setFrameShape(QFrame.HLine)
        line_hord_1.setFrameShadow(QFrame.Sunken)
        line_hord_1.setObjectName("line_hord_1")

        line_hord_3 = QFrame(self.frame_order)
        line_hord_3.setEnabled(True)
        line_hord_3.setGeometry(QRect(10, 190, 390, 16))
        line_hord_3.setFrameShape(QFrame.HLine)
        line_hord_3.setFrameShadow(QFrame.Sunken)
        line_hord_3.setObjectName("line_hord_3")

        line_hord_2 = QFrame(self.frame_order)
        line_hord_2.setEnabled(True)
        line_hord_2.setGeometry(QRect(10, 50, 390, 16))
        line_hord_2.setFrameShape(QFrame.HLine)
        line_hord_2.setFrameShadow(QFrame.Sunken)
        line_hord_2.setObjectName("line_hord_2")

        line_hord_4 = QFrame(self.frame_order)
        line_hord_4.setEnabled(True)
        line_hord_4.setGeometry(QRect(10, 330, 390, 16))
        line_hord_4.setFrameShape(QFrame.HLine)
        line_hord_4.setFrameShadow(QFrame.Sunken)
        line_hord_4.setObjectName("self.line_hord_4")

        line_vord_1 = QFrame(self.frame_order)
        line_vord_1.setEnabled(True)
        line_vord_1.setGeometry(QRect(400, 10, 20, 451))
        line_vord_1.setLineWidth(2)
        line_vord_1.setFrameShape(QFrame.VLine)
        line_vord_1.setFrameShadow(QFrame.Sunken)
        line_vord_1.setObjectName("line_vord_1")

        self.label_order_sep = QLabel(self.frame_order)
        self.label_order_sep.setEnabled(True)
        self.label_order_sep.setGeometry(QRect(220, 20, 21, 20))
        self.label_order_sep.setFont(CSS.set_font(14))
        self.label_order_sep.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_order_sep.setAlignment(Qt.AlignCenter)
        self.label_order_sep.setObjectName("label_order_sep")

        self.label_chr_num = QLabel(self.frame_order)
        self.label_chr_num.setEnabled(True)
        self.label_chr_num.setGeometry(QRect(119, 20, 41, 20))
        self.label_chr_num.setFont(CSS.set_font(14))
        self.label_chr_num.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.label_chr_num.setObjectName("label_chr_num")

        self.label_client_name = QLabel(self.frame_order)
        self.label_client_name.setEnabled(True)
        self.label_client_name.setGeometry(QRect(10, 80, *CSS.set_label_param()))
        self.label_client_name.setFont(CSS.set_font(12, True, 75))
        self.label_client_name.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_client_name.setObjectName("label_client_name")

        self.label_client_full_name = QLabel(self.frame_order)
        self.label_client_full_name.setEnabled(True)
        self.label_client_full_name.setGeometry(QRect(10, 110, 105, 20))
        self.label_client_full_name.setFont(CSS.set_font(12, True, 75))
        self.label_client_full_name.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_client_full_name.setObjectName("label_client_full_name")

        self.label_FIO_owner = QLabel(self.frame_order)
        self.label_FIO_owner.setEnabled(True)
        self.label_FIO_owner.setGeometry(QRect(10, 140, 105, 20))
        self.label_FIO_owner.setFont(CSS.set_font(12, True, 75))
        self.label_FIO_owner.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_FIO_owner.setObjectName("label_FIO_owner")

        self.label_job_title_owner = QLabel(self.frame_order)
        self.label_job_title_owner.setEnabled(True)
        self.label_job_title_owner.setGeometry(QRect(10, 170, 105, 20))
        self.label_job_title_owner.setFont(CSS.set_font(12, True, 75))
        self.label_job_title_owner.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_job_title_owner.setObjectName("label_job_title_owner")

        self.label_car_brand_number = QLabel(self.frame_order)
        self.label_car_brand_number.setEnabled(True)
        self.label_car_brand_number.setGeometry(QRect(10, 240, 105, 20))
        self.label_car_brand_number.setFont(CSS.set_font(12, True, 75))
        self.label_car_brand_number.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_car_brand_number.setObjectName("label_car_brand_number")

        self.label_model = QLabel(self.frame_order)
        self.label_model.setEnabled(True)
        self.label_model.setGeometry(QRect(10, 270, 105, 20))
        self.label_model.setFont(CSS.set_font(12, True, 75))
        self.label_model.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_model.setObjectName("label_model")

        self.label_vin_code = QLabel(self.frame_order)
        self.label_vin_code.setEnabled(True)
        self.label_vin_code.setGeometry(QRect(10, 300, 105, 20))
        self.label_vin_code.setFont(CSS.set_font(12, True, 75))
        self.label_vin_code.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.label_vin_code.setObjectName("label_vin_code")

    def retranslateUi(self):
        _translate = QCoreApplication.translate

        self.label_order_prefix.setText(_translate("MainWindow", "A"))
        self.label_order_number.setText(_translate("MainWindow", "Number"))
        self.label_order_sep.setText(_translate("MainWindow", "-"))
        self.pushButton_order_close.setText(_translate("MainWindow", "Закрыть Акт"))
        self.label_data_create.setText(_translate("MainWindow", "DATA Create"))
        self.label_chr_num.setText(_translate("MainWindow", "Акт №:"))
        self.label_client_name.setText(_translate("MainWindow", "Клиент"))
        self.label_client_full_name.setText(_translate("MainWindow", "Полное название"))
        self.label_FIO_owner.setText(_translate("MainWindow", "Представитель"))
        self.label_job_title_owner.setText(_translate("MainWindow", "Должность"))
        self.label_car_brand_number.setText(_translate("MainWindow", "Car model"))
        self.label_model.setText(_translate("MainWindow", "Car number"))
        self.label_vin_code.setText(_translate("MainWindow", "UZM number"))
        self.label_vin_code_txt.setText(_translate("MainWindow", "VIN Cod"))
        self.label_car_number_txt.setText(_translate("MainWindow", "номер"))
        self.label_car_brand_txt.setText(_translate("MainWindow", "марка"))
        self.label_client_name_txt.setText(_translate("MainWindow", "краткое название компании"))
        self.label_client_full_name_txt.setText(_translate("MainWindow", "полное название компании"))
        self.label_car_model_txt.setText(_translate("MainWindow", "модель"))
        self.radioButton_car.setText(_translate("MainWindow", "Машина"))
        self.radioButton_part.setText(_translate("MainWindow", "Запчасти"))
        self.checkBox.setText(_translate("MainWindow", "Заявка-заказ на ремонт"))
        self.checkBox_2.setText(_translate("MainWindow", "Заявка-заказ"))
        self.checkBox_3.setText(_translate("MainWindow", "Акт приемки-сдачи"))
        self.checkBox_4.setText(_translate("MainWindow", "Внутренняя накладная"))
        self.pushButton_print.setText(_translate("MainWindow", "Print"))
        self.pushButton_new_car.setText(_translate("MainWindow", "Новая\nмашина"))
        self.pushButton_new_client.setText(_translate("MainWindow", "Новый\nклиент"))

