from PyQt5 import QtWidgets, QtCore
from frame.CSS_template import CSS


class MenuBar:
    def __int__(self):
        self.menubar = QtWidgets.QMenuBar()

    def set_frame(self, frame):
        self.menubar = QtWidgets.QMenuBar(frame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 29))
        self.menubar.setStyleSheet("background-color: rgb(255, 255, 127)")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setFont(CSS.set_font(14))
        self.menuFile.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.menuHelp.setObjectName("menuHelp")
        frame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frame)
        self.statusbar.setFont(CSS.set_font(12, True, 75))
        self.statusbar.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.statusbar.setObjectName("statusbar")
        frame.setStatusBar(self.statusbar)
        self.actionPrint = QtWidgets.QAction(frame)
        self.actionPrint.setCheckable(True)
        self.actionPrint.setFont(CSS.set_font(12, False, 50))
        self.actionPrint.setObjectName("actionPrint")
        self.actionSave = QtWidgets.QAction(frame)
        self.actionSave.setCheckable(True)
        self.actionSave.setFont(CSS.set_font(12, False, 50))
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(frame)
        self.actionExit.setCheckable(True)
        self.actionExit.setFont(CSS.set_font(12, False, 50))
        self.actionExit.setObjectName("actionExit")
        self.action_2 = QtWidgets.QAction(frame)
        self.action_2.setCheckable(True)
        self.action_2.setFont(CSS.set_font(12, False, 50))
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(frame)
        self.action_3.setCheckable(True)
        self.action_3.setFont(CSS.set_font(12, False, 50))
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(frame)
        self.action_4.setCheckable(True)
        self.action_4.setFont(CSS.set_font(12, False, 50))
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(frame)
        self.action_6.setCheckable(True)
        self.action_6.setFont(CSS.set_font(12, False, 50))
        self.action_6.setObjectName("action_6")
        self.actionHelp = QtWidgets.QAction(frame)
        self.actionHelp.setCheckable(True)
        self.actionHelp.setFont(CSS.set_font(12, False, 50))
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbaut_of_programm = QtWidgets.QAction(frame)
        self.actionAbaut_of_programm.setCheckable(True)
        self.actionAbaut_of_programm.setFont(CSS.set_font(12, False, 50))
        self.actionAbaut_of_programm.setObjectName("actionAbaut_of_programm")
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.action_2)
        self.menuView.addAction(self.action_3)
        self.menuView.addAction(self.action_4)
        self.menuView.addSeparator()
        self.menuView.addAction(self.action_6)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbaut_of_programm)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.actionExit.triggered.connect(frame.close)  # type: ignore

        self.retranslateUi()

    def add_action(self):
        pass

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate

        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_2.setText(_translate("MainWindow", "Новый клиент"))
        self.action_3.setText(_translate("MainWindow", "Новая машина"))
        self.action_4.setText(_translate("MainWindow", "Новый акт"))
        self.action_6.setText(_translate("MainWindow", "Закрытые акты"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionAbaut_of_programm.setText(_translate("MainWindow", "Abaut of programm"))