# -*- coding: utf-8 -*-

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
# from kdatewidget import KDateWidget
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1280, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RootLayout = QtWidgets.QVBoxLayout()
        self.RootLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.RootLayout.setObjectName("RootLayout")
        self.MainUpFrame = QtWidgets.QFrame(self.central_widget)
        self.MainUpFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.MainUpFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.MainUpFrame.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.MainUpFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainUpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainUpFrame.setObjectName("MainUpFrame")
        self.label_4 = QtWidgets.QLabel(self.MainUpFrame)
        self.label_4.setGeometry(QtCore.QRect(181, 0, 900, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.RootLayout.addWidget(self.MainUpFrame)
        self.MainTopFrame = QtWidgets.QFrame(self.central_widget)
        self.MainTopFrame.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.MainTopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainTopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainTopFrame.setObjectName("MainTopFrame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.MainTopFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 1261, 631))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(-1, -1, 581, 631))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_5)
        self.tabWidget.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_15 = QtWidgets.QFrame(self.tab)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 571, 593))
        self.frame_15.setMinimumSize(QtCore.QSize(571, 593))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox_5.setGeometry(QtCore.QRect(100, 510, 300, 21))
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_14.setGeometry(QtCore.QRect(468, 110, 85, 71))
        self.pushButton_14.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_20 = QtWidgets.QLabel(self.frame_15)
        self.label_20.setGeometry(QtCore.QRect(10, 350, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_3.setGeometry(QtCore.QRect(128, 190, 425, 31))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_21 = QtWidgets.QLabel(self.frame_15)
        self.label_21.setGeometry(QtCore.QRect(10, 430, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_15)
        self.label_22.setGeometry(QtCore.QRect(10, 150, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_17.setGeometry(QtCore.QRect(225, 310, 85, 33))
        self.pushButton_17.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_23 = QtWidgets.QLabel(self.frame_15)
        self.label_23.setGeometry(QtCore.QRect(228, 50, 96, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_15)
        self.label_24.setGeometry(QtCore.QRect(128, 350, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_24.setObjectName("label_24")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_18.setGeometry(QtCore.QRect(453, 49, 101, 33))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.line_5 = QtWidgets.QFrame(self.frame_15)
        self.line_5.setGeometry(QtCore.QRect(3, 280, 551, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_25 = QtWidgets.QLabel(self.frame_15)
        self.label_25.setGeometry(QtCore.QRect(10, 110, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_15)
        self.label_26.setGeometry(QtCore.QRect(318, 350, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_26.setObjectName("label_26")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_19.setGeometry(QtCore.QRect(128, 310, 85, 33))
        self.pushButton_19.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_20.setGeometry(QtCore.QRect(468, 350, 85, 71))
        self.pushButton_20.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_21.setGeometry(QtCore.QRect(468, 513, 85, 71))
        self.pushButton_21.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_27 = QtWidgets.QLabel(self.frame_15)
        self.label_27.setGeometry(QtCore.QRect(358, 50, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.line_6 = QtWidgets.QFrame(self.frame_15)
        self.line_6.setGeometry(QtCore.QRect(0, 90, 551, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        # self.kdatewidget_2 = KDateWidget(self.frame_15)
        # self.kdatewidget_2.setGeometry(QtCore.QRect(193, 10, 291, 31))
        # font = QtGui.QFont()
        # font.setPointSize(14)
        # font.setBold(True)
        # font.setWeight(75)
        # self.kdatewidget_2.setFont(font)
        # self.kdatewidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.kdatewidget_2.setObjectName("kdatewidget_2")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox_6.setGeometry(QtCore.QRect(100, 480, 300, 21))
        self.checkBox_6.setObjectName("checkBox_6")
        self.label_28 = QtWidgets.QLabel(self.frame_15)
        self.label_28.setGeometry(QtCore.QRect(10, 190, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_15)
        self.label_29.setGeometry(QtCore.QRect(128, 50, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_15)
        self.label_30.setGeometry(QtCore.QRect(128, 110, 331, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_15)
        self.label_31.setGeometry(QtCore.QRect(128, 390, 331, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_15)
        self.label_32.setGeometry(QtCore.QRect(10, 390, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox_7.setGeometry(QtCore.QRect(100, 570, 300, 21))
        self.checkBox_7.setObjectName("checkBox_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_4.setGeometry(QtCore.QRect(128, 150, 333, 31))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox_8.setGeometry(QtCore.QRect(100, 540, 300, 21))
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_33 = QtWidgets.QLabel(self.frame_15)
        self.label_33.setGeometry(QtCore.QRect(333, 50, 16, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_15)
        self.label_34.setGeometry(QtCore.QRect(128, 430, 425, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_34.setObjectName("label_34")
        self.line_11 = QtWidgets.QFrame(self.frame_15)
        self.line_11.setGeometry(QtCore.QRect(10, 460, 551, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_15)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 10, 101, 81))
        self.lcdNumber.setObjectName("lcdNumber")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_16 = QtWidgets.QFrame(self.tab_2)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 571, 593))
        self.frame_16.setMinimumSize(QtCore.QSize(571, 593))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_35 = QtWidgets.QLabel(self.frame_16)
        self.label_35.setGeometry(QtCore.QRect(10, 350, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.line_7 = QtWidgets.QFrame(self.frame_16)
        self.line_7.setGeometry(QtCore.QRect(0, 90, 551, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_37 = QtWidgets.QLabel(self.frame_16)
        self.label_37.setGeometry(QtCore.QRect(10, 110, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_42 = QtWidgets.QLabel(self.frame_16)
        self.label_42.setGeometry(QtCore.QRect(10, 220, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_16)
        self.label_43.setGeometry(QtCore.QRect(10, 150, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_45 = QtWidgets.QLabel(self.frame_16)
        self.label_45.setGeometry(QtCore.QRect(10, 390, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_16)
        self.label_46.setGeometry(QtCore.QRect(10, 430, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.line_8 = QtWidgets.QFrame(self.frame_16)
        self.line_8.setGeometry(QtCore.QRect(3, 280, 551, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.pushButton_25 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_25.setGeometry(QtCore.QRect(468, 513, 85, 71))
        self.pushButton_25.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_25.setObjectName("pushButton_25")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_7.setGeometry(QtCore.QRect(128, 110, 333, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.textEdit = QtWidgets.QTextEdit(self.frame_16)
        self.textEdit.setGeometry(QtCore.QRect(128, 150, 333, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_16)
        self.textEdit_2.setGeometry(QtCore.QRect(128, 220, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_8.setGeometry(QtCore.QRect(128, 350, 333, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_9.setGeometry(QtCore.QRect(128, 390, 333, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_10.setGeometry(QtCore.QRect(128, 430, 425, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame_16)
        self.lcdNumber_2.setGeometry(QtCore.QRect(10, 10, 101, 81))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.line_12 = QtWidgets.QFrame(self.tab_2)
        self.line_12.setGeometry(QtCore.QRect(10, 460, 551, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_17 = QtWidgets.QFrame(self.tab_3)
        self.frame_17.setGeometry(QtCore.QRect(0, 0, 571, 593))
        self.frame_17.setMinimumSize(QtCore.QSize(571, 593))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_16.setGeometry(QtCore.QRect(468, 110, 85, 71))
        self.pushButton_16.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_56 = QtWidgets.QLabel(self.frame_17)
        self.label_56.setGeometry(QtCore.QRect(10, 350, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.frame_17)
        self.label_57.setGeometry(QtCore.QRect(10, 430, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.frame_17)
        self.label_58.setGeometry(QtCore.QRect(10, 150, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_26.setGeometry(QtCore.QRect(225, 310, 85, 33))
        self.pushButton_26.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_26.setObjectName("pushButton_26")
        self.line_13 = QtWidgets.QFrame(self.frame_17)
        self.line_13.setGeometry(QtCore.QRect(3, 280, 551, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_61 = QtWidgets.QLabel(self.frame_17)
        self.label_61.setGeometry(QtCore.QRect(10, 110, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.pushButton_30 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_30.setGeometry(QtCore.QRect(128, 310, 85, 33))
        self.pushButton_30.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_32 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_32.setGeometry(QtCore.QRect(468, 513, 85, 71))
        self.pushButton_32.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_32.setObjectName("pushButton_32")
        self.line_14 = QtWidgets.QFrame(self.frame_17)
        self.line_14.setGeometry(QtCore.QRect(0, 90, 551, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_66 = QtWidgets.QLabel(self.frame_17)
        self.label_66.setGeometry(QtCore.QRect(128, 110, 331, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_66.setObjectName("label_66")
        self.label_68 = QtWidgets.QLabel(self.frame_17)
        self.label_68.setGeometry(QtCore.QRect(10, 390, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.line_15 = QtWidgets.QFrame(self.frame_17)
        self.line_15.setGeometry(QtCore.QRect(10, 460, 551, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.label_71 = QtWidgets.QLabel(self.frame_17)
        self.label_71.setGeometry(QtCore.QRect(128, 150, 331, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_71.setObjectName("label_71")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit.setGeometry(QtCore.QRect(128, 350, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_2.setGeometry(QtCore.QRect(318, 350, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_11.setGeometry(QtCore.QRect(128, 390, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_12.setGeometry(QtCore.QRect(128, 430, 425, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.frame_17)
        self.lcdNumber_3.setGeometry(QtCore.QRect(10, 10, 101, 81))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame.setMinimumSize(QtCore.QSize(680, 0))
        self.frame.setMaximumSize(QtCore.QSize(680, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 681, 631))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 301, 621))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_7.setMaximumSize(QtCore.QSize(250, 30))
        self.frame_7.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setGeometry(QtCore.QRect(0, 0, 250, 30))
        self.label.setMinimumSize(QtCore.QSize(250, 30))
        self.label.setMaximumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_8.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_8.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.listWidget = QtWidgets.QListWidget(self.frame_8)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 250, 557))
        self.listWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.frame_8)
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_6.setMinimumSize(QtCore.QSize(250, 30))
        self.frame_6.setMaximumSize(QtCore.QSize(250, 30))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setGeometry(QtCore.QRect(65, 0, 117, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-bottom-color: rgb(255, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 0, 0);")
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 4, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 241, 621))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_13 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.frame_13.setMaximumSize(QtCore.QSize(200, 30))
        self.frame_13.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_3 = QtWidgets.QLabel(self.frame_13)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 200, 30))
        self.label_3.setMinimumSize(QtCore.QSize(200, 30))
        self.label_3.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.frame_12.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.listWidget_3 = QtWidgets.QListWidget(self.frame_12)
        self.listWidget_3.setGeometry(QtCore.QRect(0, 0, 200, 557))
        self.listWidget_3.setMinimumSize(QtCore.QSize(200, 0))
        self.listWidget_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_4.addWidget(self.frame_12)
        self.frame_14 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.frame_14.setMinimumSize(QtCore.QSize(200, 30))
        self.frame_14.setMaximumSize(QtCore.QSize(200, 30))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 0, 117, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-bottom-color: rgb(255, 255, 127);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.frame_14)
        self.gridLayout.addWidget(self.frame_5, 0, 5, 1, 1)
        self.a_line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.a_line.setMaximumSize(QtCore.QSize(10, 16777215))
        self.a_line.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 0, 0);")
        self.a_line.setLineWidth(1)
        self.a_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.a_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.a_line.setObjectName("a_line")
        self.gridLayout.addWidget(self.a_line, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setMaximumSize(QtCore.QSize(10, 16777215))
        self.line.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border-color: rgb(255, 0, 0);")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 202, 621))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.frame_9.setMaximumSize(QtCore.QSize(200, 30))
        self.frame_9.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 200, 30))
        self.label_2.setMinimumSize(QtCore.QSize(200, 30))
        self.label_2.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.frame_10.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_10)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 200, 557))
        self.listWidget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.listWidget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.frame_11.setMinimumSize(QtCore.QSize(200, 30))
        self.frame_11.setMaximumSize(QtCore.QSize(200, 30))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 0, 117, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-bottom-color: rgb(255, 255, 127);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.frame_11)
        self.gridLayout.addWidget(self.frame_4, 0, 3, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.RootLayout.addWidget(self.MainTopFrame)
        self.MainDownFrame = QtWidgets.QFrame(self.central_widget)
        self.MainDownFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.MainDownFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.MainDownFrame.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.MainDownFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainDownFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainDownFrame.setObjectName("MainDownFrame")
        self.pushButton_4 = QtWidgets.QPushButton(self.MainDownFrame)
        self.pushButton_4.setGeometry(QtCore.QRect(1110, 5, 117, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-bottom-color: rgb(255, 255, 127);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.MainDownFrame)
        self.pushButton_5.setGeometry(QtCore.QRect(900, 5, 117, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-bottom-color: rgb(255, 255, 127);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.MainDownFrame)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 5, 117, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-bottom-color: rgb(255, 255, 127);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.MainDownFrame)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 5, 117, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-bottom-color: rgb(255, 255, 127);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.MainDownFrame)
        self.pushButton_8.setGeometry(QtCore.QRect(290, 5, 117, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-bottom-color: rgb(255, 255, 127);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.MainDownFrame)
        self.pushButton_9.setGeometry(QtCore.QRect(410, 5, 117, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-bottom-color: rgb(255, 255, 127);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.RootLayout.addWidget(self.MainDownFrame)
        self.verticalLayout.addLayout(self.RootLayout)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 29))
        self.menubar.setStyleSheet("background-color: rgb(255, 255, 127)")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menuFile.setFont(font)
        self.menuFile.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPrint = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionPrint.setFont(font)
        self.actionPrint.setObjectName("actionPrint")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setCheckable(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setCheckable(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.action_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action_2.setFont(font)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action_3.setFont(font)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action_4.setFont(font)
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.action_6.setFont(font)
        self.action_6.setObjectName("action_6")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionHelp.setFont(font)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbaut_of_programm = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionAbaut_of_programm.setFont(font)
        self.actionAbaut_of_programm.setObjectName("actionAbaut_of_programm")
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.action_2)
        self.menuView.addAction(self.action_3)
        self.menuView.addAction(self.action_4)
        self.menuView.addSeparator()
        self.menuView.addAction(self.action_6)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbaut_of_programm)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BaseSTO"))
        self.label_4.setText(_translate("MainWindow", "Клиенты"))
        self.checkBox_5.setText(_translate("MainWindow", " -  Заявка - Заказ"))
        self.pushButton_14.setText(_translate("MainWindow", "Новый\n"
"клиент"))
        self.label_20.setText(_translate("MainWindow", "Машина"))
        self.lineEdit_3.setText(_translate("MainWindow", "Фамилия И.О."))
        self.label_21.setText(_translate("MainWindow", "VIN-код "))
        self.label_22.setText(_translate("MainWindow", "Должность"))
        self.pushButton_17.setText(_translate("MainWindow", "Запчасти"))
        self.label_23.setText(_translate("MainWindow", "000000"))
        self.label_24.setText(_translate("MainWindow", "марка машины"))
        self.pushButton_18.setText(_translate("MainWindow", "Закрыть Акт"))
        self.label_25.setText(_translate("MainWindow", "Клиент"))
        self.label_26.setText(_translate("MainWindow", "номер машины"))
        self.pushButton_19.setText(_translate("MainWindow", "Машина"))
        self.pushButton_20.setText(_translate("MainWindow", "Новая\n"
"машина"))
        self.pushButton_21.setText(_translate("MainWindow", "Распечатать"))
        self.label_27.setText(_translate("MainWindow", "А"))
        self.checkBox_6.setText(_translate("MainWindow", " -  Заявка - Заказ на ремонт"))
        self.label_28.setText(_translate("MainWindow", "ФИО заказчика"))
        self.label_29.setText(_translate("MainWindow", "Заявка №"))
        self.label_30.setText(_translate("MainWindow", "название клиента"))
        self.label_31.setText(_translate("MainWindow", "модель машины"))
        self.label_32.setText(_translate("MainWindow", "Модель"))
        self.checkBox_7.setText(_translate("MainWindow", " -  Внутренняя накладная"))
        self.lineEdit_4.setText(_translate("MainWindow", "должность"))
        self.checkBox_8.setText(_translate("MainWindow", " -  Акт приёмки-сдачи"))
        self.label_33.setText(_translate("MainWindow", "-"))
        self.label_34.setText(_translate("MainWindow", "VIN код машины"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_35.setText(_translate("MainWindow", "УНП клиента"))
        self.label_37.setText(_translate("MainWindow", "Клиент"))
        self.label_42.setText(_translate("MainWindow", "Адрес почты"))
        self.label_43.setText(_translate("MainWindow", "Название"))
        self.label_45.setText(_translate("MainWindow", "Телефон"))
        self.label_46.setText(_translate("MainWindow", "Мобильный"))
        self.pushButton_25.setText(_translate("MainWindow", "Сохранить"))
        self.lineEdit_7.setText(_translate("MainWindow", "клиент"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">полное название клиента</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Адрес</span></p></body></html>"))
        self.lineEdit_8.setText(_translate("MainWindow", "УНП клиента"))
        self.lineEdit_9.setText(_translate("MainWindow", "городской телефон"))
        self.lineEdit_10.setText(_translate("MainWindow", "мобильный номер клиента"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.pushButton_16.setText(_translate("MainWindow", "Новый\n"
"клиент"))
        self.label_56.setText(_translate("MainWindow", "Машина"))
        self.label_57.setText(_translate("MainWindow", "VIN-код "))
        self.label_58.setText(_translate("MainWindow", "УНП клиента"))
        self.pushButton_26.setText(_translate("MainWindow", "Запчасти"))
        self.label_61.setText(_translate("MainWindow", "Клиент"))
        self.pushButton_30.setText(_translate("MainWindow", "Машина"))
        self.pushButton_32.setText(_translate("MainWindow", "Сохранить"))
        self.label_66.setText(_translate("MainWindow", "Владелец машины"))
        self.label_68.setText(_translate("MainWindow", "Модель"))
        self.label_71.setText(_translate("MainWindow", "УНП клиента"))
        self.lineEdit.setText(_translate("MainWindow", "марка машины"))
        self.lineEdit_2.setText(_translate("MainWindow", "Номер машины"))
        self.lineEdit_11.setText(_translate("MainWindow", "модель машины"))
        self.lineEdit_12.setText(_translate("MainWindow", "VIN код машины"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Страница"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Страница"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Страница"))
        self.label.setText(_translate("MainWindow", "Клиенты"))
        self.frame_6.setStyleSheet(_translate("MainWindow", "background-color: rgb(85, 170, 0);"))
        self.pushButton.setText(_translate("MainWindow", "Обновить"))
        self.label_3.setText(_translate("MainWindow", "Акты"))
        self.frame_14.setStyleSheet(_translate("MainWindow", "background-color: rgb(85, 170, 0);"))
        self.pushButton_3.setText(_translate("MainWindow", "Обновить"))
        self.label_2.setText(_translate("MainWindow", "Машина клиента"))
        self.frame_11.setStyleSheet(_translate("MainWindow", "background-color: rgb(85, 170, 0);"))
        self.pushButton_2.setText(_translate("MainWindow", "Обновить"))
        self.pushButton_4.setText(_translate("MainWindow", "Exit"))
        self.pushButton_5.setText(_translate("MainWindow", "Справка"))
        self.pushButton_6.setText(_translate("MainWindow", "....."))
        self.pushButton_7.setText(_translate("MainWindow", "....."))
        self.pushButton_8.setText(_translate("MainWindow", "....."))
        self.pushButton_9.setText(_translate("MainWindow", "....."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_2.setText(_translate("MainWindow", "Новый клиент"))
        self.action_3.setText(_translate("MainWindow", "Новая машина"))
        self.action_4.setText(_translate("MainWindow", "Новый акт"))
        self.action_6.setText(_translate("MainWindow", "Закрытые акты"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionAbaut_of_programm.setText(_translate("MainWindow", "Abaut of programm"))


def Main():
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    Main()

